namespace Decent.Minecraft.Client
{
    /// <summary>
    /// Minecraft entity types.
    /// The byte values correspond to actual Minecraft entity IDs.
    /// <a href="http://minecraft.gamepedia.com/Data_values/Entity_IDs">Gamepedia link</a>.
    /// </summary>
    public enum EntityType : byte
    {
        Item = 1,
        XPOrb,
        AreaEffectCloud,
        ElderGuardian,
        WitherSkeleton,
        Stray,
        Egg,
        LeashKnot,
        Painting,
        Arrow,
        Snowball,
        Fireball,
        SmallFireball,
        EnderPearl,
        EyeOfEnder,
        Potion,
        XPBottle,
        ItemFrame,
        WitherSkull,
        PrimedTnt,
        FallingBlock,
        FireworksRocket,
        Husk,
        SpectralArrow,
        ShulkerBullet,
        DragonFireball,
        ZombieVillager,
        SkeletonHorse,
        ZombieHorse,
        ArmorStand,
        Donkey,
        Mule,
        EvocationFangs,
        Evoker,
        Vex,
        Vindicator,
        MinecartWithCommandBlock = 40,
        Boat,
        Minecart,
        MinecartWithChest,
        MinecartWithFurnace,
        MinecartWithTNT,
        MinecartWithHopper,
        MinecartWithSpawner,
        Human = 49,
        Creeper,
        Skeleton,
        Spider,
        Giant,
        Zombie,
        Slime,
        Ghast,
        ZombiePigman,
        Enderman,
        CaveSpider,
        Silverfish,
        Blaze,
        MagmaCube,
        EnderDragon,
        Wither,
        Bat,
        Witch,
        Endermite,
        Guardian,
        Shulker,
        Pig = 90,
        Sheep,
        Cow,
        Chicken,
        Squid,
        Wolf,
        Mooshroom,
        SnowGolem,
        Ocelot,
        IronGolem,
        Horse,
        Rabbit,
        PolarBear,
        Llama,
        Villager = 120,
        EnderCrystal = 200,
        ThePlayer = 255 // This one actually isn't defined on the Minecraft side.
    }
}
