namespace Decent.Minecraft.Client
{
    public enum BlockType : byte
    {
        Air = 0,
        Stone,
        Grass,
        Dirt,
        Cobblestone,
        WoodPlanks,
        Sapling,
        Bedrock,
        WaterFlowing = 8,
        Water = 8,
        WaterStationary = 9,
        LavaFlowing = 10,
        Lava = 10,
        LavaStationary = 11,
        Sand,
        Gravel,
        GoldOre,
        IronOre,
        CoalOre,
        Wood,
        Leaves,
        Glass = 20,
        LapisLazuliOre,
        LapisLazuliBlock,
        Sandstone = 24,
        Bed = 26,
        Cobweb = 30,
        GrassTall,
        Wool = 35,
        FlowerYellow = 37,
        FlowerCyan,
        MushroomBrown,
        MushroomRed,
        GoldBlock,
        IronBlock,
        StoneSlabDouble,
        StoneSlab,
        BrickBlock,
        TNT,
        Bookshelf,
        MossStone,
        Obsidian,
        Torch,
        Fire,
        StairsWood = 53,
        Chest,
        DiamondOre = 56,
        DiamondBlock,
        CraftingTable,
        Farmland = 60,
        FurnaceInactive,
        FurnaceActive,
        DoorWood = 64,
        Ladder,
        StairsCobblestone = 67,
        DoorIron = 71,
        RedstoneOre = 73,
        Snow = 78,
        Ice,
        SnowBlock,
        Cactus,
        Clay,
        SugarCane,
        Fence = 85,
        GlowstoneBlock = 89,
        BedrockInvisible = 95,
        StoneBrick = 98,
        GlassPane = 102,
        Melon,
        FenceGate = 107,
        GlowingObsidian = 246,
        NetherReactorCore
    }
}